pipeline:
  name: Build go-pipeline-sample
  identifier: Build_priyanka10009_go_pipeline_sample_1777460124104
  projectIdentifier: Lloyds_Project_POC
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: run unit tests
                  identifier: Echo_Welcome_Message
                  spec:
                    connectorRef: <+input>
                    image: golang:1.15
                    shell: Sh
                    command: |-
                      set +e
                      go get gotest.tools/gotestsum
                      gotestsum --format=standard-verbose --junitfile unit-tests.xml
                      exit 0
                      ``
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "*.xml"
              - step:
                  type: Run
                  name: build app
                  identifier: build_app
                  spec:
                    connectorRef: <+input>
                    image: golang:1.15
                    shell: Sh
                    command: |-
                      set +e
                      go get gotest.tools/gotestsum
                      CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo
                      exit 0
              - step:
                  type: BuildAndPushDockerRegistry
                  name: build and push image to dockerhub
                  identifier: build_and_push_image_to_dockerhub
                  spec:
                    connectorRef: <+input>
                    repo: <+input>
                    tags:
                      - latest
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1777459475967
        repoName: priyanka10009/go-pipeline-sample
        build: <+input>
        sparseCheckout: []
